"""The pure game model: colors, the board, where cubes sit, and the clue language."""

from chroma_cube.core.board import BOARD_4X4, BOARD_4X5, CLASSIC_BOARD, Board, Cell
from chroma_cube.core.clues import (
    ATTRIBUTE_KINDS,
    BOARD_RULE_KINDS,
    PROPERTY_KINDS,
    REGION_KINDS,
    RELATION_KINDS,
    And,
    AtLeast,
    AttributeClue,
    AttributeKind,
    BoardRule,
    BoardRuleKind,
    Clue,
    ColorRef,
    Exactly,
    Not,
    Or,
    Property,
    PropertyKind,
    Region,
    Relation,
    RelationKind,
    attribute,
    attribute_clues,
    prop,
    ref,
    regions,
    relation,
)
from chroma_cube.core.colors import (
    CLASSIC_PALETTE,
    EXTENDED_16,
    EXTENDED_20,
    FAMILIES,
    PALETTES,
    QUALITIES,
    TEMPERATURES,
    TONES,
    Color,
    Palette,
    attributes_from_hex,
)
from chroma_cube.core.evaluate import Truth, evaluate
from chroma_cube.core.parse import ClueParseError, parse_clue, parse_clues
from chroma_cube.core.placement import Placement
from chroma_cube.core.puzzle import Puzzle, puzzle_from_dict, puzzle_to_dict
from chroma_cube.core.render import render
from chroma_cube.core.serialize import clue_from_dict, clue_to_dict

__all__ = [
    "ATTRIBUTE_KINDS",
    "REGION_KINDS",
    "AttributeClue",
    "AttributeKind",
    "Region",
    "attribute",
    "attribute_clues",
    "regions",
    "BOARD_4X4",
    "BOARD_4X5",
    "EXTENDED_16",
    "EXTENDED_20",
    "FAMILIES",
    "PALETTES",
    "QUALITIES",
    "TEMPERATURES",
    "TONES",
    "attributes_from_hex",
    "BOARD_RULE_KINDS",
    "CLASSIC_BOARD",
    "CLASSIC_PALETTE",
    "PROPERTY_KINDS",
    "RELATION_KINDS",
    "And",
    "AtLeast",
    "Board",
    "BoardRule",
    "BoardRuleKind",
    "Cell",
    "Clue",
    "ClueParseError",
    "Color",
    "ColorRef",
    "Exactly",
    "Not",
    "Or",
    "Palette",
    "Placement",
    "Property",
    "Puzzle",
    "PropertyKind",
    "Relation",
    "RelationKind",
    "Truth",
    "clue_from_dict",
    "clue_to_dict",
    "evaluate",
    "parse_clue",
    "parse_clues",
    "prop",
    "puzzle_from_dict",
    "puzzle_to_dict",
    "ref",
    "relation",
    "render",
]
